-- Maps to: ENG-004, FR-002, NFR-007

ALTER TABLE public.era_detections
  ADD COLUMN IF NOT EXISTS prompt_token_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS candidates_token_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_token_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS api_call_count INTEGER NOT NULL DEFAULT 0;
